/* Automatically generated by './build/bin/build-entry.js' */

import Aside from "../packages/aside/index.js";
import Button from "../packages/button/index.js";
import Col from "../packages/col/index.js";
import Footer from "../packages/footer/index.js";
import Header from "../packages/header/index.js";
import Main from "../packages/main/index.js";
import Row from "../packages/row/index.js";
import Scrollbar from "../packages/scrollbar/index.js";
import Select from "../packages/select/index.js";
import Container from "../packages/container/index.js";
import locale from "phoon-ui/src/locale";

const components = [Aside, Button, Col, Footer, Header, Main, Row, Scrollbar, Select, Container];

const install = function(Vue, opts = {}) {
	locale.use(opts.locale);
	locale.i18n(opts.i18n);

	components.forEach((component) => {
		Vue.component(component.name, component);
	});
};

if (typeof window !== "undefined" && window.Vue) {
	install(window.Vue);
}

// 导出版本号、Install方法（插件）和一些功能
export default {
	version: "1.0.0",
	locale: locale.i18n,
	install,
	Aside,
	Button,
	Col,
	Footer,
	Header,
	Main,
	Row,
	Scrollbar,
	Select,
	Container,
};
